# This file was generated by GoReleaser. DO NOT EDIT.
cask "sinq-bin" do
  version "1.0.0-rc.22"

  on_macos do
    on_intel do
      sha256 "5a215ba53c542a2c6ff8ee788d09ccefb052cb631f6915dab4ce811e90d72977"
      url "https://github.com/Veitangie/sinq/releases/download/v#{version}/sinq-#{version}-macOS-x86_64.tar.gz"
    end
    on_arm do
      sha256 "95114d9bfee43da88d7bf47f90c60507ae4108163f247bc334a5dcec6ee1633a"
      url "https://github.com/Veitangie/sinq/releases/download/v#{version}/sinq-#{version}-macOS-arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "6ae5c8c05214c065c238e19014079bd8dd687defe618f50a1e97bb5d675f8a0b"
      url "https://github.com/Veitangie/sinq/releases/download/v#{version}/sinq-#{version}-linux-x86_64.tar.gz"
    end
    on_arm do
      sha256 "a761e2681403ae72e8631ebcd9e8f236564f563f3e5ef0f7d7e5a05a4942b99a"
      url "https://github.com/Veitangie/sinq/releases/download/v#{version}/sinq-#{version}-linux-arm64.tar.gz"
    end
  end

  name "sinq-bin"
  desc "A concurrent HTTP functional and integration testing tool."
  homepage "https://github.com/Veitangie/sinq"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "sinq-bin"
  manpage "sinq.1"

  # No zap stanza required

end
