# This file was generated by GoReleaser. DO NOT EDIT.
cask "sinq" do
  version "1.0.0-rc.11"

  on_macos do
    on_intel do
      sha256 "e2047b249fab60ed00bd6562f045e307805172c830d4f2ad9048275168723019"
      url "https://github.com/Veitangie/sinq/releases/download/v#{version}/sinq-#{version}-macOS-x86_64.tar.gz"
    end
    on_arm do
      sha256 "a49e079d85e7f60190ad7806c34e2d3a5b406ed6e96e2fb28efdebcc9c11df9f"
      url "https://github.com/Veitangie/sinq/releases/download/v#{version}/sinq-#{version}-macOS-arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "e59e2d7d0c6022e4b5c60be173f08cda94f14f86e4724ebb6acdc1d6df7734f0"
      url "https://github.com/Veitangie/sinq/releases/download/v#{version}/sinq-#{version}-linux-x86_64.tar.gz"
    end
    on_arm do
      sha256 "ed9e851a540918dfcdcc60fac4c76614da1bd9f61946a87a505c8249f0d5dd1e"
      url "https://github.com/Veitangie/sinq/releases/download/v#{version}/sinq-#{version}-linux-arm64.tar.gz"
    end
  end

  name "sinq"
  desc "A concurrent HTTP functional and integration testing tool."
  homepage "https://github.com/Veitangie/sinq"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "sinq"
  manpage "sinq.1"

  # No zap stanza required

end
