# This file was generated by GoReleaser. DO NOT EDIT.
cask "sinq" do
  version "1.0.0-rc.11"

  on_macos do
    on_intel do
      sha256 "f57f3c5e373629ae4e0f9a10ce4bdd1318c9c7ce0c750b92b9d2c2f1075a77a7"
      url "https://github.com/Veitangie/sinq/releases/download/v#{version}/sinq-#{version}-macOS-x86_64.tar.gz"
    end
    on_arm do
      sha256 "b7a7a8016cbe979fcbb103126ddc32690187365fd698b7562b07bf62643c9c11"
      url "https://github.com/Veitangie/sinq/releases/download/v#{version}/sinq-#{version}-macOS-arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "319a3184d850788877b87f7ceb56861481f9ce5c482208fd5ab0f51c28b88b33"
      url "https://github.com/Veitangie/sinq/releases/download/v#{version}/sinq-#{version}-linux-x86_64.tar.gz"
    end
    on_arm do
      sha256 "181b6b9a476596216cfe1c421d919fd9d2060ed77809ab55599bc55c107445b9"
      url "https://github.com/Veitangie/sinq/releases/download/v#{version}/sinq-#{version}-linux-arm64.tar.gz"
    end
  end

  name "sinq"
  desc "A concurrent HTTP functional and integration testing tool."
  homepage "https://github.com/Veitangie/sinq"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "sinq"
  manpage "sinq.1"

  # No zap stanza required

end
