# This file was generated by GoReleaser. DO NOT EDIT.
cask "sinq-bin" do
  version "1.0.0-rc.17"

  on_macos do
    on_intel do
      sha256 "6fcf071c04247d24f796ef437ccd16bfb1a13c0c3b8267d40f9553dad17a8358"
      url "https://github.com/Veitangie/sinq/releases/download/v#{version}/sinq-#{version}-macOS-x86_64.tar.gz"
    end
    on_arm do
      sha256 "990bd81de1a308cc3932b467bd45b01538c1cc59ecfa0e843fed8d70b8283fd8"
      url "https://github.com/Veitangie/sinq/releases/download/v#{version}/sinq-#{version}-macOS-arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "6f331749bdfef0f6d9a6fbfd049d7d3f445f14abd78d35ecd72c47b9587ca919"
      url "https://github.com/Veitangie/sinq/releases/download/v#{version}/sinq-#{version}-linux-x86_64.tar.gz"
    end
    on_arm do
      sha256 "b02dd7ea7ab45f8e3595ca4274814705f9ad1e9f3b86c90c02eb66cecd1d256b"
      url "https://github.com/Veitangie/sinq/releases/download/v#{version}/sinq-#{version}-linux-arm64.tar.gz"
    end
  end

  name "sinq-bin"
  desc "A concurrent HTTP functional and integration testing tool."
  homepage "https://github.com/Veitangie/sinq"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "sinq-bin"
  manpage "sinq.1"

  # No zap stanza required

end
