# This file was generated by GoReleaser. DO NOT EDIT.
cask "sinq" do
  version "1.0.0-rc.12"

  on_macos do
    on_intel do
      sha256 "544e0ba19c6a608319d72433f4615d5702bcbfac8959b01fb6f6bb79763ce7d8"
      url "https://github.com/Veitangie/sinq/releases/download/v#{version}/sinq-#{version}-macOS-x86_64.tar.gz"
    end
    on_arm do
      sha256 "28fdce66b27bd37c6b8f2b313243d6573d56d739ad6325d5d2bffa87ed1ede9b"
      url "https://github.com/Veitangie/sinq/releases/download/v#{version}/sinq-#{version}-macOS-arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "ac4f1642122fe549525c4f4db4106a2f9118b68dadea99121ad814ec97e68bca"
      url "https://github.com/Veitangie/sinq/releases/download/v#{version}/sinq-#{version}-linux-x86_64.tar.gz"
    end
    on_arm do
      sha256 "87096bf59af05a7489e2445fad210693fb4c03b9ed9949ac96368fcb80d2ddf1"
      url "https://github.com/Veitangie/sinq/releases/download/v#{version}/sinq-#{version}-linux-arm64.tar.gz"
    end
  end

  name "sinq"
  desc "A concurrent HTTP functional and integration testing tool."
  homepage "https://github.com/Veitangie/sinq"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "sinq"
  manpage "sinq.1"

  # No zap stanza required

end
