# This file was generated by GoReleaser. DO NOT EDIT.
cask "sinq-bin" do
  version "1.0.0-rc.14"

  on_macos do
    on_intel do
      sha256 "2fea231ea883325a80dd959e56e7638f8c71199a3c6031200169aababbd6bf74"
      url "https://github.com/Veitangie/sinq/releases/download/v#{version}/sinq-#{version}-macOS-x86_64.tar.gz"
    end
    on_arm do
      sha256 "d9c9cd7392b5a8508b2c566643ebc08190d8cd780f57d883397604b8f727ad7a"
      url "https://github.com/Veitangie/sinq/releases/download/v#{version}/sinq-#{version}-macOS-arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "20728011f2ec3fdaf7d6103a4652cf00e7fc037412d5ba8f4671bb42c3309eb2"
      url "https://github.com/Veitangie/sinq/releases/download/v#{version}/sinq-#{version}-linux-x86_64.tar.gz"
    end
    on_arm do
      sha256 "7a7717d50fe1d59589f2a19ccc17f2a4968eb6a0dde3142e2343b10d3cf0908b"
      url "https://github.com/Veitangie/sinq/releases/download/v#{version}/sinq-#{version}-linux-arm64.tar.gz"
    end
  end

  name "sinq-bin"
  desc "A concurrent HTTP functional and integration testing tool."
  homepage "https://github.com/Veitangie/sinq"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "sinq-bin"
  manpage "sinq.1"

  # No zap stanza required

end
