# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sinq < Formula
  desc "A concurrent HTTP functional and integration testing tool."
  homepage "https://github.com/Veitangie/sinq"
  version "1.0.0-rc.3"
  license "GPL-3.0-only"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Veitangie/sinq/releases/download/v1.0.0-rc.3/sinq-1.0.0-rc.3-macOS-x86_64.tar.gz"
      sha256 "c76176ab719a64808205d74fedf872f321df256c53fba2064cccd2ebaf8ae77e"

      define_method(:install) do
        bin.install "sinq"
        man1.install "sinq.1"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Veitangie/sinq/releases/download/v1.0.0-rc.3/sinq-1.0.0-rc.3-macOS-arm64.tar.gz"
      sha256 "9dcb8b5062f741d7f9ecb9506406eb2e2b0855acfc384047334b787b4bd5fd31"

      define_method(:install) do
        bin.install "sinq"
        man1.install "sinq.1"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Veitangie/sinq/releases/download/v1.0.0-rc.3/sinq-1.0.0-rc.3-linux-x86_64.tar.gz"
      sha256 "45bcc450faf36c81ccec901df12a45d2f4ec9f274e580b4073c7f3bb0ddb2d8a"
      define_method(:install) do
        bin.install "sinq"
        man1.install "sinq.1"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Veitangie/sinq/releases/download/v1.0.0-rc.3/sinq-1.0.0-rc.3-linux-arm64.tar.gz"
      sha256 "839af1701f40ccda721a53f2b27640367221c616c5e2137892c407e40b80d83b"
      define_method(:install) do
        bin.install "sinq"
        man1.install "sinq.1"
      end
    end
  end
end
